[platformio]
default_envs = esp8266

[common]
framework = arduino
lib_ldf_mode = deep+
lib_deps =
    home-assistant-integration=symlink://../..

[env:esp8266]
extends = common
platform = espressif8266
board = d1_mini
platform_packages =
    platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git#521ae60a89e64bb0d1eb7a0b7addf620ced5cad3

[env:esp32]
extends = common
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.05/platform-espressif32.zip
board = esp32dev
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++14
    -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/Network/src
